# default.yml controls global settings and policies/reports that run on all hosts ("All fleets").

policies:
reports:
agent_options:
controls:
org_settings:
  fleet_desktop:
    transparency_url: "https://catoftheday.com"
  host_expiry_settings:
    host_expiry_enabled: true
    host_expiry_window: 30
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: Qausar GitOps
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
  webhook_settings:
    activities_webhook:
      enable_activities_webhook: true
      destination_url: "https://webhook.site/c4a9bd93-f802-41e1-828c-20b117e2becb"
